services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: meli_test-server
    container_name: meli_test-server
    volumes:
      - ./server:/app
      - server-node_modules:/app/node_modules
    ports:
      - "8000:3000"
    env_file: ./server/.env
    restart: unless-stopped
    command: npm run dev
    networks:
      - meli_test-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: meli_test-client
    container_name: meli_test-client
    volumes:
      - ./client:/app
      - client-node_modules:/app/node_modules
    ports:
      - "3000:3000"
    env_file: ./client/.env
    restart: unless-stopped
    command: npm run start
    stdin_open: true
    networks:
      - meli_test-network

networks:
  meli_test-network:
    driver: bridge

volumes:
  server-node_modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./server/node_modules

  client-node_modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./client/node_modules
